### ISSUE TITLE
After I finished the deployment, I couldn't access the web page, and no errors were shown during the deployment process.

### ISSUE THREAD

**Issue by zhouyujn** [microsoft/call-center-ai#336] opened 2024-10-22 12:23 UTC
@clemlesne , After I finished the deployment, I couldn't access the web page, and no errors were shown during the deployment process.

I found the following error inside the container app.

{"TimeStamp":"2024-10-22T12:18:41Z","Type":"Normal","ContainerAppName":null,"RevisionName":null,"ReplicaName":null,"Msg":"Connecting to the events collector...","Reason":"StartingGettingEvents","EventSource":"ContainerAppController","Count":1}
{"TimeStamp":"2024-10-22T12:18:42Z","Type":"Normal","ContainerAppName":null,"RevisionName":null,"ReplicaName":null,"Msg":"Successfully connected to events server","Reason":"ConnectedToEventsServer","EventSource":"ContainerAppController","Count":1}
{"TimeStamp":"2024-10-22 12:18:21 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--0000001","ReplicaName":"call-center-ai--0000001-84d9655cc7-tcnrx","Msg":"Readiness Probe with executor HttpGetExecutor reached failure threshold 3, changing status to Failure.","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":1}
{"TimeStamp":"2024-10-22 12:18:21 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--0000001","ReplicaName":"call-center-ai--0000001-84d9655cc7-sr7mm","Msg":"Readiness Probe with executor HttpGetExecutor reached failure threshold 3, changing status to Failure.","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":1}
{"TimeStamp":"2024-10-22 12:18:21 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--0000001","ReplicaName":"call-center-ai--0000001-84d9655cc7-sr7mm","Msg":"Probe with executor HttpGetExecutor failed with status code: 503","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":3}
{"TimeStamp":"2024-10-22 12:18:29 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--y9qkfok","ReplicaName":"call-center-ai--y9qkfok-54d997449b-jw4xt","Msg":"Probe with executor HttpGetExecutor failed with status code: 503","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":3}
{"TimeStamp":"2024-10-22 12:18:29 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--y9qkfok","ReplicaName":"call-center-ai--y9qkfok-54d997449b-jw4xt","Msg":"Container call-center-ai failed readiness probe","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":1}
{"TimeStamp":"2024-10-22 12:18:29 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--y9qkfok","ReplicaName":"call-center-ai--y9qkfok-54d997449b-jw4xt","Msg":"Readiness Probe with executor HttpGetExecutor reached failure threshold 3, changing status to Failure.","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":1}
{"TimeStamp":"2024-10-22 12:18:40 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--0000001","ReplicaName":"call-center-ai--0000001-84d9655cc7-sr7mm","Msg":"Probe with executor HttpGetExecutor failed with status code: 503","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":4}
{"TimeStamp":"2024-10-22 12:18:40 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--0000001","ReplicaName":"call-center-ai--0000001-84d9655cc7-tcnrx","Msg":"Probe with executor HttpGetExecutor failed with status code: 503","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":4}
{"TimeStamp":"2024-10-22 12:18:49 \u002B0000 UTC","Type":"Warning","ContainerAppName":"call-center-ai","RevisionName":"call-center-ai--y9qkfok","ReplicaName":"call-center-ai--y9qkfok-54d997449b-jw4xt","Msg":"Probe with executor HttpGetExecutor failed with status code: 503","Reason":"ProbeFailed","EventSource":"ContainerAppController","Count":4}

**Comment by clemlesne** [comment] 2024-10-22 13:55
It seems that the health check failed. Can you dig in App Insights to share the error/exceptions in that issue?

**Comment by zhouyujn** [comment] 2024-10-22 15:05
There are indeed quite a few errors.
It seems to be an issue with connecting to Cosmos, but I haven't found any problems on the Cosmos side.



Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span
    yield span
  File "/venv/lib/python3.12/site-packages/azure/core/tracing/decorator_async.py", line 105, in wrapper_use_tracer
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/cosmos/aio/_container.py", line 304, in read_item
    return await self.client_connection.ReadItem(document_link=doc_link, options=request_options, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/cosmos/aio/_cosmos_client_connection_async.py", line 959, in ReadItem
    return await self.Read(path, "docs", document_id, None, options, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/cosmos/aio/_cosmos_client_connection_async.py", line 1147, in Read
    result, last_response_headers = await self.__Get(path, request_params, headers, **kwargs)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/cosmos/aio/_cosmos_client_connection_async.py", line 1169, in __Get
    return await asynchronous_request.AsynchronousRequest(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/cosmos/aio/_asynchronous_request.py", line 172, in AsynchronousRequest
    return await _retry_utility_async.ExecuteAsync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/cosmos/aio/_retry_utility_async.py", line 83, in ExecuteAsync
    result = await ExecuteFunctionAsync(function, global_endpoint_manager, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/cosmos/aio/_retry_utility_async.py", line 148, in ExecuteFunctionAsync
    return await function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/azure/cosmos/aio/_asynchronous_request.py", line 117, in _Request
    raise exceptions.CosmosResourceNotFoundError(message=data, response=response)
azure.cosmos.exceptions.CosmosResourceNotFoundError: (NotFound) Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found, {"Summary":{"DirectCalls":{"(404, 0)":1}},"name":"HandleDocumentRequest","id":"d25ce27e-9567-412c-b785-097f8410e1f8","start time":"02:43:46:465","duration in milliseconds":32.3533,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus2-be131.documents.azure.com:14052/apps/8d843a25-abb7-41ae-89a6-13fe3269619d/services/1ae923e8-8e2d-48dc-8b33-73650cf30bbc/partitions/1741ed79-206c-41a0-b31c-536a90333fd7/replicas/133740565141827283s/"}],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[{"ResponseTimeUTC":"2024-10-22T14:43:46.4977797Z","ResourceType":"Document","OperationType":"Read","LocationEndpoint":"https://callcenter-zhouyujndemo-eastus2.sql.cosmos.azure.com/","StoreResult":{"ActivityId":"7c1a59af-ea93-4dc8-86aa-439857e22a93","StatusCode":"NotFound","SubStatusCode":"Unknown","LSN":1298,"PartitionKeyRangeId":"0","GlobalCommittedLSN":1297,"ItemLSN":-1,"UsingLocalLSN":true,"QuorumAckedLSN":-1,"SessionToken":"-1#1298","CurrentWriteQuorum":-1,"CurrentReplicaSetSize":-1,"NumberOfReadRegions":0,"IsValid":true,"StorePhysicalAddress":"rntbd://cdb-ms-prod-eastus2-be131.documents.azure.com:14052/apps/8d843a25-abb7-41ae-89a6-13fe3269619d/services/1ae923e8-8e2d-48dc-8b33-73650cf30bbc/partitions/1741ed79-206c-41a0-b31c-536a90333fd7/replicas/133740565141827283s/","RequestCharge":1,"RetryAfterInMs":null,"BELatencyInMs":"21.125","transportRequestTimeline":{"requestTimeline":[{"event": "Created", "startTimeUtc": "2024-10-22T14:43:46.4655556Z", "durationInMs": 0.0023},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2024-10-22T14:43:46.4655579Z", "durationInMs": 10.4079},{"event": "Pipelined", "startTimeUtc": "2024-10-22T14:43:46.4759658Z", "durationInMs": 0.0514},{"event": "Transit Time", "startTimeUtc": "2024-10-22T14:43:46.4760172Z", "durationInMs": 21.7216},{"event": "Received", "startTimeUtc": "2024-10-22T14:43:46.4977388Z", "durationInMs": 0.0286},{"event": "Completed", "startTimeUtc": "2024-10-22T14:43:46.4977674Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"True","callsPendingReceive":0,"lastSendAttempt":"2024-10-22T14:43:46.4750220Z","lastSend":"2024-10-22T14:43:46.4750474Z","lastReceive":"2024-10-22T14:43:46.4755241Z"},"requestSizeInBytes":1975,"responseMetadataSizeInBytes":190,"responseBodySizeInBytes":84},"TransportException":null}}]}}}, Windows/10.0.20348 cosmos-netstandard-sdk/3.18.0
Code: NotFound
Message: Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found, {"Summary":{"DirectCalls":{"(404, 0)":1}},"name":"HandleDocumentRequest","id":"d25ce27e-9567-412c-b785-097f8410e1f8","start time":"02:43:46:465","duration in milliseconds":32.3533,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus2-be131.documents.azure.com:14052/apps/8d843a25-abb7-41ae-89a6-13fe3269619d/services/1ae923e8-8e2d-48dc-8b33-73650cf30bbc/partitions/1741ed79-206c-41a0-b31c-536a90333fd7/replicas/133740565141827283s/"}],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[{"ResponseTimeUTC":"2024-10-22T14:43:46.4977797Z","ResourceType":"Document","OperationType":"Read","LocationEndpoint":"https://callcenter-zhouyujndemo-eastus2.sql.cosmos.azure.com/","StoreResult":{"ActivityId":"7c1a59af-ea93-4dc8-86aa-439857e22a93","StatusCode":"NotFound","SubStatusCode":"Unknown","LSN":1298,"PartitionKeyRangeId":"0","GlobalCommittedLSN":1297,"ItemLSN":-1,"UsingLocalLSN":true,"QuorumAckedLSN":-1,"SessionToken":"-1#1298","CurrentWriteQuorum":-1,"CurrentReplicaSetSize":-1,"NumberOfReadRegions":0,"IsValid":true,"StorePhysicalAddress":"rntbd://cdb-ms-prod-eastus2-be131.documents.azure.com:14052/apps/8d843a25-abb7-41ae-89a6-13fe3269619d/services/1ae923e8-8e2d-48dc-8b33-73650cf30bbc/partitions/1741ed79-206c-41a0-b31c-536a90333fd7/replicas/133740565141827283s/","RequestCharge":1,"RetryAfterInMs":null,"BELatencyInMs":"21.125","transportRequestTimeline":{"requestTimeline":[{"event": "Created", "startTimeUtc": "2024-10-22T14:43:46.4655556Z", "durationInMs": 0.0023},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2024-10-22T14:43:46.4655579Z", "durationInMs": 10.4079},{"event": "Pipelined", "startTimeUtc": "2024-10-22T14:43:46.4759658Z", "durationInMs": 0.0514},{"event": "Transit Time", "startTimeUtc": "2024-10-22T14:43:46.4760172Z", "durationInMs": 21.7216},{"event": "Received", "startTimeUtc": "2024-10-22T14:43:46.4977388Z", "durationInMs": 0.0286},{"event": "Completed", "startTimeUtc": "2024-10-22T14:43:46.4977674Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"True","callsPendingReceive":0,"lastSendAttempt":"2024-10-22T14:43:46.4750220Z","lastSend":"2024-10-22T14:43:46.4750474Z","lastReceive":"2024-10-22T14:43:46.4755241Z"},"requestSizeInBytes":1975,"responseMetadataSizeInBytes":190,"responseBodySizeInBytes":84},"TransportException":null}}]}}}, Windows/10.0.20348 cosmos-netstandard-sdk/3.18.0

**Comment by Laki4Ever79** [comment] 2024-10-22 15:41
From my experience it appears that this Cosmos DB role is deprecated:
https://github.com/microsoft/call-center-ai/blob/main/cicd%2Fbicep%2Fapp.bicep#L755

**Comment by zhouyujn** [comment] 2024-10-22 15:45
I have manually added the permissions for this role to the Cantain app.

**Comment by Laki4Ever79** [comment] 2024-10-22 15:51
I did as well and still faced "RBAC permission denied" error when I tried reading accessing CosmosDB metadata, for some reason.

**Comment by clemlesne** [comment] 2024-10-22 16:10
The error you’re reporting @zhouyujn is not a bug, the implementation uses the `NotFound` error to detect if the document doesn’t exist:

https://github.com/microsoft/call-center-ai/blob/7e5de4c1ae67bf6610ad55e150825733e68f6e11/app/persistence/cosmos_db.py#L76-L84

Any issue like `NotAuthorized` would signify a permission issue. If your deployment receives `NotFound`, well, the access is granted.

Are there any additional errors?

**Comment by clemlesne** [comment] 2024-10-22 16:11
@Laki4Ever79 what permission did you specifically added?

**Comment by Laki4Ever79** [comment] 2024-10-22 16:44
I've added Cosmos DB Account Reader Role and Cosmos DB Operator for my Azure Cosmos DB account and this is the error I get:
ERROR:call-center-ai:Error accessing CosmosDB: (Forbidden) Request blocked by Auth ai-call-center : Request is blocked because principal [...] does not have required RBAC permissions to perform action [Microsoft.DocumentDB/databaseAccounts/readMetadata] on resource [/]. Learn more: https://aka.ms/cosmos-native-rbac.
ActivityId: ..., Microsoft.Azure.Documents.Common/2.14.0
Code: Forbidden

**Comment by zhouyujn** [comment] 2024-10-23 01:19
@Laki4Ever79 

Have you tried adding it with this command?

https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/security/how-to-grant-data-plane-role-based-access?tabs=built-in-definition%2Ccsharp&pivots=azure-interface-cli

**Comment by zhouyujn** [comment] 2024-10-23 03:17
I noticed a strange issue during operations in CosmosDB. The PartitionKey keeps using the old +33612345678, but I have already changed the PartitionKey to the new phone number from the communication service.

![Image](https://github.com/user-attachments/assets/1b93cd52-7443-434a-aa79-efcb0091910a)

![Image](https://github.com/user-attachments/assets/5cbe021f-594c-4e83-902e-caf9c850f35d)

**Comment by zhouyujn** [comment] 2024-10-23 13:05
I would like to know where this URL （https://callcenter-zhouyujndemo-eastus2.sql.cosmos.azure.com/）was generated. It is not consistent with the endpoint shown in the portal.
I remember this format is usually https://<your-account-name>.<region>.documents.azure.com/ or https://<your-account-name>.<region>.sql.cosmos.azure.com/.



azure.cosmos.exceptions.CosmosResourceNotFoundError: (NotFound) Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found, {"Summary":{"DirectCalls":{"(404, 0)":1}},"name":"HandleDocumentRequest","id":"6bef4b48-78ac-4768-9f29-801f1e800ec9","start time":"12:59:52:425","duration in milliseconds":21.2773,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-eastus2-be131.documents.azure.com:14140/apps/8d843a25-abb7-41ae-89a6-13fe3269619d/services/1ae923e8-8e2d-48dc-8b33-73650cf30bbc/partitions/1741ed79-206c-41a0-b31c-536a90333fd7/replicas/133740565141827284s/"}],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[{"ResponseTimeUTC":"2024-10-23T12:59:52.4463681Z","ResourceType":"Document","OperationType":"Read","**LocationEndpoint":"https://callcenter-zhouyujndemo-eastus2.sql.cosmos.azure.com/**","StoreResult":{"ActivityId":"db8441ae-1ae8-453f-9121-40bf6a249752","StatusCode":"NotFound","SubStatusCode":"Unknown","LSN":9336,"PartitionKeyRangeId":"0","GlobalCommittedLSN":9335,"ItemLSN":-1,"UsingLocalLSN":true,"QuorumAckedLSN":-1,"SessionToken":"-1#9336","CurrentWriteQuorum":-1,"CurrentReplicaSetSize":-1,"NumberOfReadRegions":0,"IsValid":true,"StorePhysicalAddress":"rntbd://cdb-ms-prod-eastus2-be131.documents.azure.com:14140/apps/8d843a25-abb7-41ae-89a6-13fe3269619d/services/1ae923e8-8e2d-48dc-8b33-73650cf30bbc/partitions/1741ed79-206c-41a0-b31c-536a90333fd7/replicas/133740565141827284s/","RequestCharge":1,"RetryAfterInMs":null,"BELatencyInMs":"20.628","transportRequestTimeline":{"requestTimeline":[{"event": "Created", "startTimeUtc": "2024-10-23T12:59:52.4252250Z", "durationInMs": 0.0025},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2024-10-23T12:59:52.4252275Z", "durationInMs": 0.0025},{"event": "Pipelined", "startTimeUtc": "2024-10-23T12:59:52.4252300Z", "durationInMs": 0.0574},{"event": "Transit Time", "startTimeUtc": "2024-10-23T12:59:52.4252874Z", "durationInMs": 21.037},{"event": "Received", "startTimeUtc": "2024-10-23T12:59:52.4463244Z", "durationInMs": 0.0324},{"event": "Completed", "startTimeUtc": "2024-10-23T12:59:52.4463568Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"False","callsPendingReceive":0,"lastSendAttempt":"2024-10-23T12:59:52.3205167Z","lastSend":"2024-10-23T12:59:52.3205522Z","lastReceive":"2024-10-23T12:59:52.3414904Z"},"requestSizeInBytes":1975,"responseMetadataSizeInBytes":190,"responseBodySizeInBytes":84},"TransportException":null}}]}}}, Windows/10.0.20348 cosmos-netstandard-sdk/3.18.0
Code: NotFound

**Comment by clemlesne** [comment] 2024-10-25 17:52
I deployed from scratch the app in a separated environment. It appears that it is working well, out of the box, _if you follow all the steps_.

But, it appears also that the health-check fails if AI Search is nos properly configured. That was intended (if not, what is the purpose of a readiness health check?). This was specified in the README. With that configured, the application runs well.

https://github.com/microsoft/call-center-ai/blob/7e5de4c1ae67bf6610ad55e150825733e68f6e11/README.md?plain=1#L360-L363

To ease the life of everyone, I published in a breaking change an automation to automatically build the index and configure it. You can install the `v12.0.0`.

Please, send me feedbacks? Is it better now?

**Comment by clemlesne** [comment] 2024-11-28 08:31
Closing for now. Don't hesitate to reopen if needed.

**Closed** 2024-11-28 08:32 UTC
Labels: question
